### ISSUE TITLE
osx-64 R3.5.1 package not uploaded despite CI success

### ISSUE THREAD

**Issue by dbast** [conda-forge/r-usethis-feedstock#1]
The osx-64 R3.5.1 package did not got uploaded after the feedstock registration, even though CI finished without error.

Details:
* The not-upload osx-64 R3.5.1 CI run: https://travis-ci.com/conda-forge/r-usethis-feedstock/jobs/154978612
* The uploaded osx-64 R3.4.1 CI run: https://travis-ci.com/conda-forge/r-usethis-feedstock/jobs/154978611

Both runs report: "Distribution /Users/travis/miniconda3/conda-bld/osx-64/r-usethis-1.4.0-r341h6115d3f_0.tar.bz2 is new for conda-forge, but no upload is taking place because the BINSTAR_TOKEN is missing."  ...which does not make so much sense to me... and the token is there in the conda-forge.yml 

I also did re-trigger travis... with the same result... the osx-64 R3.5.1 file is not uploaded ... https://anaconda.org/conda-forge/r-usethis/files

**Comment by cbrueffer** [comment]
Seems to have been an intermittent problems; the package is available now.

**Comment by jdblischak** [comment]
@dbast @cbrueffer That is strange though. Both the error message and the fact that one of the packages wasn't uploaded until 15 hours after the others.

<img width="980" alt="screen shot 2018-10-30 at 9 37 28 am" src="https://user-images.githubusercontent.com/1608317/47721904-8485da00-dc27-11e8-919c-394ba5a02567.png">

@dbast Is this the first time you've observed this? Let's hope it's just intermittent.

**Comment by cbrueffer** [comment]
@jdblischak the upload happened as a result of re-triggering the CI build.

**Comment by jdblischak** [comment]
> the upload happened as a result of re-triggering the CI build.

@cbrueffer Thanks for the clarification. I see now why I was confused. I clicked on the GitHub link about Travis CI, which sent me to the old build page:

https://travis-ci.com/conda-forge/r-usethis-feedstock/jobs/154978612#L650

Now following the Travis link directly from the commit leads me to the latest build:

https://travis-ci.org/conda-forge/r-usethis-feedstock/jobs/448032375#L652

**Comment by dbast** [comment]
Ok. Thanks everyone!
